// Generated by CoffeeScript 1.3.1
(function() {
  var assert;

  assert = require('assert');

  suite('Send event', function() {
    test('Check if log message can be written to file', function(done) {
      var fileHandler, fs, testConfig;
      fs = require('fs');
      testConfig = {
        file: '/tmp/test'
      };
      fileHandler = require('../lib/logger/file');
      return fileHandler({}, testConfig, 'Test message', {
        test: 'object'
      }, 'test', function() {
        return fs.stat(testConfig.file, function(error, stats) {
          assert.ifError(error);
          assert.notEqual(stats.size, 0, 'Empty log file, write failed');
          return fs.unlink(testConfig.file, function() {
            return done();
          });
        });
      });
    });
    return test('Check if log message can send to email', function(done) {
      var emailHandler, testConfig, testMonitorConfig;
      this.timeout(10000);
      emailHandler = require('../lib/logger/email');
      testMonitorConfig = {
        project: 'Test'
      };
      testConfig = {
        enabled: true,
        email: 'voronchuk@gmail.com',
        mailer: {
          service: 'SendGrid',
          auth: {
            user: 'voronchuk',
            pass: '[jvgjllth',
            handler: emailHandler
          }
        }
      };
      return emailHandler(testMonitorConfig, testConfig, 'Test message', {
        test: 'object'
      }, 'test', function(error) {
        assert.ifError(error);
        return done();
      });
    });
  });

}).call(this);
