// Generated by CoffeeScript 1.3.1
(function() {

  module.exports = function(monitorConfig, config, message, object, type, callback) {
    var createMessage, fs, path, _;
    _ = require('underscore');
    fs = require('fs');
    path = require('path');
    createMessage = function(message, object, type) {
      var text, util;
      if (type == null) {
        type = 'message';
      }
      text = new Date().toString() + (":" + type + ": " + message + "\n");
      if (!((_.isUndefined(object)) || _.isNull(object))) {
        util = require('util');
        text += util.inspect(object);
        text += "\n";
      }
      return text += "\n";
    };
    return fs.open(config.file, 'a', 0x1a4, function(error, fd) {
      var buffer;
      if (error) {
        callback(error);
        return;
      }
      buffer = new Buffer(createMessage(message, object, type));
      return fs.write(fd, buffer, 0, buffer.length, null, function(error, written) {
        if (error) {
          callback(error);
          return;
        }
        return fs.close(fd, callback);
      });
    });
  };

}).call(this);
