// Generated by CoffeeScript 1.3.1
(function() {

  module.exports = function(monitorConfig, config, message, object, type, callback) {
    var buffer, createMessage, fd, fs, path, _;
    _ = require('underscore');
    fs = require('fs');
    path = require('path');
    createMessage = function(message, object, type) {
      var text, util;
      if (type == null) {
        type = 'message';
      }
      text = new Date().toString() + (":" + type + ": " + message + "\n");
      if (!((_.isUndefined(object)) || _.isNull(object))) {
        util = require('util');
        text += util.inspect(object);
        text += "\n";
      }
      return text += "\n";
    };
    fd = fs.openSync(config.file, 'a', 0x1a4);
    buffer = new Buffer(createMessage(message, object, type));
    return fs.write(fd, buffer, 0, buffer.length, null, function() {
      fs.close(fd);
      return callback();
    });
  };

}).call(this);
