// Generated by CoffeeScript 1.3.1
(function() {
  var fs, path, _;

  _ = require('underscore');

  fs = require('fs');

  path = require('path');

  module.exports = function(callback) {
    var pid;
    pid = "/proc/" + process.pid + "/stat";
    if (!path.existsSync(pid)) {
      callback(null, 1);
      console.log('CPU monitor works only on Linux systems');
      return;
    }
    return fs.readFile(pid, function(error, data) {
      var elems, stime, utime;
      elems = data.toString().split(' ');
      utime = parseInt(elems[13]);
      stime = parseInt(elems[14]);
      return callback(error, utime + stime);
    });
  };

}).call(this);
